baseURL = "/"
languageCode = "en-us"
title = "APSIM Next Generation"


[Params]
  noCategoryLink = true
  
  
[[menu.main]]
  name   = "Model documentation"
  url    = "http://www.apsim.info/APSIM.Builds.Service/Builds.svc/GetDocumentationHTML"
  weight = 1
  
[[menu.main]]  
  name   = "Development"
  url    = "/development/index"
  weight = 2  

  